spring:
  application:
    name: bet-api-service
  datasource:
    url: jdbc:postgresql://localhost:5432/betting
    username: betting
    password: betting
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
    consumer:
      group-id: bet-api-service
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "br.devrodrigues.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
  topics:
    bet-placed: bets.placed.v1
    game-created: games.created.v1
    matches-result: matches.result.v1
  kafka:
    consumer-groups:
      matches-result: bet-api-service-matches
  outbox:
    batch-size: 100
    publisher-delay-ms: 2000

management:
  endpoints:
    web:
      exposure:
        include: health,info
