spring:
  application:
    name: bet-api-service
  datasource:
    url: jdbc:postgresql://localhost:5432/betting
    username: betting
    password: betting
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}

server:
  port: 8080

app:
  topics:
    bet-placed: bet.placed
  outbox:
    batch-size: 100
    publisher-delay-ms: 2000

management:
  endpoints:
    web:
      exposure:
        include: health,info
