spring:
  application:
    name: bet-settlement-service
  datasource:
    url: jdbc:postgresql://localhost:5433/bet_settlement
    username: settlement
    password: settlement
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8082

app:
  topics:
    game-created: games.created.v1
