spring:
  application:
    name: bet-settlement-service
  datasource:
    url: jdbc:postgresql://localhost:5433/bet_settlement
    username: settlement
    password: settlement
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
    consumer:
      group-id: bet-settlement-service
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "br.devrodrigues.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  topics:
    bet-placed: bets.placed.v1
    game-created: games.created.v1
    matches-result: matches.result.v1
    matches-result-dlq: matches.result.dlq
  settlement:
    worker-delay-ms: 2000
